# Generated by Django 4.1.5 on 2023-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='picture',
            field=models.ImageField(default='auctions/listing/default_listing.png', upload_to='auctions/static/auctions/listing/'),
        ),
    ]
