# Generated by Django 4.1.5 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='picture',
            field=models.ImageField(default='auctions/default_listing.png', upload_to='auctions/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='auctions/default_avatar.png', upload_to='auctions/'),
        ),
    ]
