# Generated by Django 4.1.5 on 2023-02-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionlisting_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Arts & Crafts, DIY', 'Arts & Crafts, DIY'), ('Automotive & Industrial', 'Automotive & Industrial'), ('Baby & Child Care', 'Baby & Child Care'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books & Office Supplies', 'Books & Office Supplies'), ('Electronics & Technology', 'Electronics & Technology'), ('Fashion & Clothing', 'Fashion & Clothing'), ('Fiction & Magic', 'Fiction & Magic'), ('Food & Beverage', 'Food & Beverage'), ('Garden & Outdoor Living', 'Garden & Outdoor Living'), ('Health & Wellness', 'Health & Wellness'), ('Home & Kitchen', 'Home & Kitchen'), ('Music & Entertainment', 'Music & Entertainment'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games'), ('Other', 'Other')], max_length=50, verbose_name='category'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_listing', to='auctions.auctionlisting', verbose_name='Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL, verbose_name='Watching')),
            ],
        ),
    ]
