# Generated by Django 4.1.5 on 2023-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auctionlisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[(None, 'Choose category'), ('Arts & Crafts, DIY', 'Arts & Crafts, DIY'), ('Automotive & Industrial', 'Automotive & Industrial'), ('Baby & Child Care', 'Baby & Child Care'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books & Office Supplies', 'Books & Office Supplies'), ('Electronics & Technology', 'Electronics & Technology'), ('Fashion & Clothing', 'Fashion & Clothing'), ('Fiction & Magic', 'Fiction & Magic'), ('Food & Beverage', 'Food & Beverage'), ('Garden & Outdoor Living', 'Garden & Outdoor Living'), ('Health & Wellness', 'Health & Wellness'), ('Home & Kitchen', 'Home & Kitchen'), ('Music & Entertainment', 'Music & Entertainment'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games'), ('Other', 'Other')], max_length=50, verbose_name='category'),
        ),
    ]
