# Generated by Django 4.1.5 on 2023-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlisting_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='commerce/auctions/media/profile/default_avatar.png', upload_to='profile/'),
        ),
    ]
