# Generated by Django 4.1.5 on 2023-02-23 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_auctionlisting_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='closed',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
    ]
