# Generated by Django 4.1.5 on 2023-04-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Post Content')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
            ],
        ),
    ]
