# Generated by Django 4.1.5 on 2023-04-12 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5a01cb07-97c8-46e2-8239-833c6a07f9f2'), editable=False, verbose_name='UUID'),
        ),
    ]
