# Generated by Django 4.1.5 on 2023-04-12 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9e839e1e-07c9-450d-802c-2dc23a94694e'), verbose_name='UUID'),
        ),
    ]
