# Generated by Django 4.1.5 on 2023-04-12 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d8a50b2-59a6-4d85-8a2d-f11adc0d3408'), verbose_name='UUID'),
        ),
    ]
