# Generated by Django 4.1.5 on 2023-04-12 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ef0b93b9-364d-46bc-872a-cd2a5fa1176c'), verbose_name='Universally Unique IDentifier'),
        ),
    ]
