# Generated by Django 4.1.5 on 2023-04-12 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6d09b06-2f97-4ef9-9055-84891f75f8e6'), verbose_name='Universally Unique IDentifier (UUID)'),
        ),
    ]
