# Generated by Django 4.1.5 on 2023-04-12 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae7ecde3-f839-4517-b742-2c40c10d64b1'), editable=False, verbose_name='Universally Unique IDentifier (UUID)'),
        ),
    ]
